- hosts: vm
  become: yes
  become_user: root
  become_method: su
  tasks:
    - name: apt update and upgrade all VM's and baremetal servers
      apt:
        update_cache: yes
        upgrade: 'yes'
